### ISSUE TITLE
Suggestion SketchUp

### ISSUE THREAD

**Issue by wernight** [mbasso/awesome-wasm#115]
I think https://app.sketchup.com/app is also Wasm and it's pretty awesome.

**Comment by mbasso** [comment]
Hi @wernight,
Thank you for opening this issue 😄 
I've tried to search for some resources that point out the usage of Wasm to develop sketch, but I've found nothing for now. Could you please provide some articles (or whatever) before adding it to the list?

**Comment by ThomasTheDane** [comment]
They were referenced in the 2019 Chrome Dev Summit wasm talk: https://www.youtube.com/watch?v=zgOGZgAPUjQ

**Comment by mbasso** [comment]
Hi @ThomasTheDane,
Cool, I didn't remember about that, I'll add it to list right now 😄
