### ISSUE TITLE
CONTRIBUTING.md has a dead link

### ISSUE THREAD

**Issue by efx** [mbasso/awesome-wasm#127]
**General Information**
While reading CONTRIBUTING.md, I tried to navigate to http://titlecapitalization.com/ but it does not appear to be up.
- [x] Bug
- [ ] Improvement
- [ ] Other

**Description**
I propose we link to another source for defining title case.

**Comment by mbasso** [comment]
Hi @efx,
thank you for opening this issue. I'll find an alternative to that site and open a PR as soon as possible!
