### ISSUE TITLE
Add year to old links?

### ISSUE THREAD

**Issue by binji** [mbasso/awesome-wasm#2]
**General Information**

- [ ] Bug
- [ ] Improvement
- [X] Other

**Description**

Some of the links are relatively old (2015), from prior to the initial release. As a result, a lot of the information will be incorrect. I think it's fine to keep those links around, but it might help to mention the year in the name of the link:

e.g.
- What is WebAssembly (2015)
- 7 Things You Should Know About WebAssembly (2015)

etc.

**Comment by mbasso** [comment]
Hi,
yes, I think that this is a great idea. I'll add the year at every link in "articles", "video", "tutorial", "slides" and other that are not code. Also, I can sort them, putting the newest on the top of the list. I'll do it as soon as possible, probably tonight.

**Comment by binji** [comment]
Cool, thanks!

**Comment by mbasso** [comment]
@binji resources are now sorted by year and have the following format: `Title (year)` 🎉 
I've done this for the following sections:
- Tutorials
- Articles
- Video
- Slides

Let me know if it is ok or if you have any suggestions
