### ISSUE TITLE
Link to WebAssembly Studio leads dangerous site

### ISSUE THREAD

**Issue by eckertliam** [mbasso/awesome-wasm#200]
**General Information**

- [ ] Bug
- [x] Improvement
- [ ] Other

**Description**
The link for WebAssembly Studio leads to a dangerous site. The address has clearly been sold and the link should be removed.

**Comment by Yee1023** [comment]
邮件我已收到，谢谢！！

**Comment by mbasso** [comment]
Hi @eckertliam,

I have removed it, thank you!
