### ISSUE TITLE
Section Online Playground has broken links

### ISSUE THREAD

**Issue by AlgorithmEnigma** [mbasso/awesome-wasm#218]
**General Information**

- [X] Bug
- [ ] Improvement
- [ ] Other

**Description**
Section Online Playground has broken links:

[WebAssembly Playground](http://ast.run/) leads to a purchase domain ad.
[WasmFiddle](https://wasdk.github.io/WasmFiddle/) leads to a GitHub 404.

**Comment by mbasso** [comment]
Thank you for opening this issue!
I'll fix it ASAP
