### ISSUE TITLE
Section for web frameworks

### ISSUE THREAD

**Issue by erlend-sh** [mbasso/awesome-wasm#54]
**General Information**

- [ ] Bug
- [x] Improvement
- [ ] Other

**Description**

Should there be a section dedicated to web frameworks? I can think of at least theee notable frameworks that I didn’t see listed here:

https://github.com/DenisKolodin/yew
https://github.com/aspnet/blazor
https://github.com/jpmorganchase/perspective

(Sorry if they’re actually there, I’m on mobile)

**Comment by mbasso** [comment]
Hi @erlend-sh,
just renamed the "DOM" section, moved Blazor and added yew and perspective.
Thank you for opening this issue 😄
