### ISSUE TITLE
Travis build broken by SSL certificate of one of sites

### ISSUE THREAD

**Issue by vkradio** [mbasso/awesome-wasm#59]
**General Information**

- [x] Bug
- [ ] Improvement
- [ ] Other

**Description**

While creating PR #58 there was a failure in Travis build, it complains to SSL certificate of one of the sites in overall list, pls see https://github.com/mbasso/awesome-wasm/pull/58#issuecomment-373909670

**Comment by mbasso** [comment]
Hi @vkradio,
thank you for opening this issue.
I think that we can fix the build in 2 ways:
- replace `https` with `http` for that resource
- add the `--allow-ssl` option to the [awesome_bot](https://github.com/dkhamsing/awesome_bot#command-line) config to ignore that error
What do you think?

**Comment by vkradio** [comment]
I've tried to replace `https` to `http`, that game will not run. So I think we can suppress error for that string if it is possible.

**Comment by mbasso** [comment]
I've tried [http://funkykarts.rocks/demo.html](http://funkykarts.rocks/demo.html) and it works fine for me, can you please check it?
I'm not sure, but I think that we can suppress the error with the [`--white-list`](https://github.com/dkhamsing/awesome_bot#command-line) option

**Comment by vkradio** [comment]
I've tried this version (`http` without `www`), and checked it with Fiddler. It shows that:

1. `http` / -> redirects (301) to `http` /fLMYb/demo.html
2. `http` /fLMYb/demo.html -> redirects (301) to `http` /demo.html
3. `http` /demo.html -> redirects (302) to `https` https://www.funkykarts.rocks/demo.html
and so thats it.

So if bot is able to traverse all this path, it may be ok.

**Comment by vkradio** [comment]
Or may be bot will be satisfied with just step 1 and then stop as happy?

**Comment by mbasso** [comment]
I think that the bot will be satisfied with just step 1 as you said, but I haven't found enough documentation to make me sure. We can just try this solution.
If it doesn't work, we have to use the `--white-list` option

**Comment by mbasso** [comment]
Just fixed replacing `https` with `http`, thank you very much for contributing 🎉
