### ISSUE TITLE
new book on WebAssembly!

### ISSUE THREAD

**Issue by zstauber** [mbasso/awesome-wasm#89]
**General Information**

- [ ] Bug
- [* ] Improvement
- [ ] Other

**Description**
There is a new book to add!  Learn WebAssembly.  It is to my knowledge the first full length published [electronic] book on WebAssembly.  It is not free, but still it may be of interest to WebAssembly students.  I am planning to order it right now.  Thank you for this Git Hub list, it's great.
https://www.packtpub.com/web-development/learn-webassembly

(Add images if possible)

**Comment by mbasso** [comment]
Awesome, thank you! 😄
I'll create a PR for this!
